# Generated by Django 5.2.17 on 2026-08-29 11:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=255)),
                ('image', models.ImageField(default='', upload_to='adverts/', verbose_name='Оголошення')),
                ('datetime_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('datetime_to', models.DateTimeField(default=django.utils.timezone.now)),
                ('priority', models.IntegerField(choices=[('info', 'Інформаційне'), ('reklama', 'Рекламне'), ('social', 'Соціальне'), ('admin', 'Адміністративне')], default='info')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
