# Generated by Django 5.2.17 on 2026-09-19 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='priority',
            field=models.CharField(choices=[('info', 'Інформаційне'), ('reklama', 'Рекламне'), ('social', 'Соціальне'), ('admin', 'Адміністративне')], default='info', max_length=255),
        ),
    ]
