# Generated by Django 6.0.6 on 2026-09-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='can_upload',
            field=models.BooleanField(default=True),
        ),
    ]
