# Generated by Django 6.0.6 on 2026-09-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Заголовок')),
                ('content', models.TextField(verbose_name='Текст новини')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news_photos/')),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
